INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (1, NOW(), NOW(), 'AC/DC') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (2, NOW(), NOW(), 'Accept') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (3, NOW(), NOW(), 'Aerosmith') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (4, NOW(), NOW(), 'Alanis Morissette') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (5, NOW(), NOW(), 'Alice In Chains') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (6, NOW(), NOW(), 'Ant�nio Carlos Jobim') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (7, NOW(), NOW(), 'Apocalyptica') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (8, NOW(), NOW(), 'Audioslave') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (9, NOW(), NOW(), 'BackBeat') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (10, NOW(), NOW(), 'Billy Cobham') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (11, NOW(), NOW(), 'Black Label Society') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (12, NOW(), NOW(), 'Black Sabbath') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (13, NOW(), NOW(), 'Body Count') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (14, NOW(), NOW(), 'Bruce Dickinson') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (15, NOW(), NOW(), 'Buddy Guy') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (16, NOW(), NOW(), 'Caetano Veloso') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (17, NOW(), NOW(), 'Chico Buarque') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (18, NOW(), NOW(), 'Chico Science & Na��o Zumbi') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (19, NOW(), NOW(), 'Cidade Negra') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (20, NOW(), NOW(), 'Cl�udio Zoli') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (21, NOW(), NOW(), 'Various Artists') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (22, NOW(), NOW(), 'Led Zeppelin') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (23, NOW(), NOW(), 'Frank Zappa & Captain Beefheart') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (24, NOW(), NOW(), 'Marcos Valle') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (25, NOW(), NOW(), 'Milton Nascimento & Bebeto') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (26, NOW(), NOW(), 'Azymuth') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (27, NOW(), NOW(), 'Gilberto Gil') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (28, NOW(), NOW(), 'Jo�o Gilberto') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (29, NOW(), NOW(), 'Bebel Gilberto') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (30, NOW(), NOW(), 'Jorge Vercilo') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (31, NOW(), NOW(), 'Baby Consuelo') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (32, NOW(), NOW(), 'Ney Matogrosso') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (33, NOW(), NOW(), 'Luiz Melodia') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (34, NOW(), NOW(), 'Nando Reis') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (35, NOW(), NOW(), 'Pedro Lu�s & A Parede') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (36, NOW(), NOW(), 'O Rappa') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (37, NOW(), NOW(), 'Ed Motta') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (38, NOW(), NOW(), 'Banda Black Rio') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (39, NOW(), NOW(), 'Fernanda Porto') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (40, NOW(), NOW(), 'Os Cariocas') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (41, NOW(), NOW(), 'Elis Regina') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (42, NOW(), NOW(), 'Milton Nascimento') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (43, NOW(), NOW(), 'A Cor Do Som') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (44, NOW(), NOW(), 'Kid Abelha') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (45, NOW(), NOW(), 'Sandra De S�') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (46, NOW(), NOW(), 'Jorge Ben') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (47, NOW(), NOW(), 'Hermeto Pascoal') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (48, NOW(), NOW(), 'Bar�o Vermelho') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (49, NOW(), NOW(), 'Edson, DJ Marky & DJ Patife Featuring Fernanda Porto') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (50, NOW(), NOW(), 'Metallica') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (51, NOW(), NOW(), 'Queen') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (52, NOW(), NOW(), 'Kiss') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (53, NOW(), NOW(), 'Spyro Gyra') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (54, NOW(), NOW(), 'Green Day') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (55, NOW(), NOW(), 'David Coverdale') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (56, NOW(), NOW(), 'Gonzaguinha') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (57, NOW(), NOW(), 'Os Mutantes') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (58, NOW(), NOW(), 'Deep Purple') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (59, NOW(), NOW(), 'Santana') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (60, NOW(), NOW(), 'Santana Feat. Dave Matthews') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (61, NOW(), NOW(), 'Santana Feat. Everlast') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (62, NOW(), NOW(), 'Santana Feat. Rob Thomas') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (63, NOW(), NOW(), 'Santana Feat. Lauryn Hill & Cee-Lo') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (64, NOW(), NOW(), 'Santana Feat. The Project G&B') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (65, NOW(), NOW(), 'Santana Feat. Man�') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (66, NOW(), NOW(), 'Santana Feat. Eagle-Eye Cherry') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (67, NOW(), NOW(), 'Santana Feat. Eric Clapton') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (68, NOW(), NOW(), 'Miles Davis') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (69, NOW(), NOW(), 'Gene Krupa') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (70, NOW(), NOW(), 'Toquinho & Vin�cius') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (71, NOW(), NOW(), 'Vin�cius De Moraes & Baden Powell') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (72, NOW(), NOW(), 'Vin�cius De Moraes') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (73, NOW(), NOW(), 'Vin�cius E Qurteto Em Cy') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (74, NOW(), NOW(), 'Vin�cius E Odette Lara') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (75, NOW(), NOW(), 'Vinicius, Toquinho & Quarteto Em Cy') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (76, NOW(), NOW(), 'Creedence Clearwater Revival') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (77, NOW(), NOW(), 'C�ssia Eller') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (78, NOW(), NOW(), 'Def Leppard') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (79, NOW(), NOW(), 'Dennis Chambers') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (80, NOW(), NOW(), 'Djavan') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (81, NOW(), NOW(), 'Eric Clapton') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (82, NOW(), NOW(), 'Faith No More') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (83, NOW(), NOW(), 'Falamansa') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (84, NOW(), NOW(), 'Foo Fighters') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (85, NOW(), NOW(), 'Frank Sinatra') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (86, NOW(), NOW(), 'Funk Como Le Gusta') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (87, NOW(), NOW(), 'Godsmack') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (88, NOW(), NOW(), 'Guns '' Roses') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (89, NOW(), NOW(), 'Incognito') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (90, NOW(), NOW(), 'Iron Maiden') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (91, NOW(), NOW(), 'James Brown') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (92, NOW(), NOW(), 'Jamiroquai') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (93, NOW(), NOW(), 'JET') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (94, NOW(), NOW(), 'Jimi Hendrix') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (95, NOW(), NOW(), 'Joe Satriani') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (96, NOW(), NOW(), 'Jota Quest') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (97, NOW(), NOW(), 'Jo�o Suplicy') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (98, NOW(), NOW(), 'Judas Priest') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (99, NOW(), NOW(), 'Legi�o Urbana') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (100, NOW(), NOW(), 'Lenny Kravitz') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (101, NOW(), NOW(), 'Lulu Santos') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (102, NOW(), NOW(), 'Marillion') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (103, NOW(), NOW(), 'Marisa Monte') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (104, NOW(), NOW(), 'Marvin Gaye') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (105, NOW(), NOW(), 'Men At Work') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (106, NOW(), NOW(), 'Mot�rhead') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (107, NOW(), NOW(), 'Mot�rhead & Girlschool') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (108, NOW(), NOW(), 'M�nica Marianno') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (109, NOW(), NOW(), 'M�tley Cr�e') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (110, NOW(), NOW(), 'Nirvana') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (111, NOW(), NOW(), 'O Ter�o') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (112, NOW(), NOW(), 'Olodum') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (113, NOW(), NOW(), 'Os Paralamas Do Sucesso') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (114, NOW(), NOW(), 'Ozzy Osbourne') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (115, NOW(), NOW(), 'Page & Plant') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (116, NOW(), NOW(), 'Passengers') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (117, NOW(), NOW(), 'Paul D''Ianno') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (118, NOW(), NOW(), 'Pearl Jam') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (119, NOW(), NOW(), 'Peter Tosh') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (120, NOW(), NOW(), 'Pink Floyd') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (121, NOW(), NOW(), 'Planet Hemp') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (122, NOW(), NOW(), 'R.E.M. Feat. Kate Pearson') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (123, NOW(), NOW(), 'R.E.M. Feat. KRS-One') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (124, NOW(), NOW(), 'R.E.M.') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (125, NOW(), NOW(), 'Raimundos') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (126, NOW(), NOW(), 'Raul Seixas') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (127, NOW(), NOW(), 'Red Hot Chili Peppers') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (128, NOW(), NOW(), 'Rush') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (129, NOW(), NOW(), 'Simply Red') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (130, NOW(), NOW(), 'Skank') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (131, NOW(), NOW(), 'Smashing Pumpkins') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (132, NOW(), NOW(), 'Soundgarden') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (133, NOW(), NOW(), 'Stevie Ray Vaughan & Double Trouble') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (134, NOW(), NOW(), 'Stone Temple Pilots') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (135, NOW(), NOW(), 'System Of A Down') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (136, NOW(), NOW(), 'Terry Bozzio, Tony Levin & Steve Stevens') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (137, NOW(), NOW(), 'The Black Crowes') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (138, NOW(), NOW(), 'The Clash') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (139, NOW(), NOW(), 'The Cult') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (140, NOW(), NOW(), 'The Doors') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (141, NOW(), NOW(), 'The Police') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (142, NOW(), NOW(), 'The Rolling Stones') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (143, NOW(), NOW(), 'The Tea Party') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (144, NOW(), NOW(), 'The Who') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (145, NOW(), NOW(), 'Tim Maia') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (146, NOW(), NOW(), 'Tit�s') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (147, NOW(), NOW(), 'Battlestar Galactica') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (148, NOW(), NOW(), 'Heroes') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (149, NOW(), NOW(), 'Lost') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (150, NOW(), NOW(), 'U2') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (151, NOW(), NOW(), 'UB40') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (152, NOW(), NOW(), 'Van Halen') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (153, NOW(), NOW(), 'Velvet Revolver') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (154, NOW(), NOW(), 'Whitesnake') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (155, NOW(), NOW(), 'Zeca Pagodinho') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (156, NOW(), NOW(), 'The Office') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (157, NOW(), NOW(), 'Dread Zeppelin') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (158, NOW(), NOW(), 'Battlestar Galactica (Classic)') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (159, NOW(), NOW(), 'Aquaman') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (160, NOW(), NOW(), 'Christina Aguilera featuring BigElf') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (161, NOW(), NOW(), 'Aerosmith & Sierra Leone''s Refugee Allstars') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (162, NOW(), NOW(), 'Los Lonely Boys') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (163, NOW(), NOW(), 'Corinne Bailey Rae') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (164, NOW(), NOW(), 'Dhani Harrison & Jakob Dylan') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (165, NOW(), NOW(), 'Jackson Browne') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (166, NOW(), NOW(), 'Avril Lavigne') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (167, NOW(), NOW(), 'Big & Rich') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (168, NOW(), NOW(), 'Youssou ''Dour') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (169, NOW(), NOW(), 'Black Eyed Peas') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (170, NOW(), NOW(), 'Jack Johnson') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (171, NOW(), NOW(), 'Ben Harper') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (172, NOW(), NOW(), 'Snow Patrol') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (173, NOW(), NOW(), 'Matisyahu') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (174, NOW(), NOW(), 'The Postal Service') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (175, NOW(), NOW(), 'Jaguares') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (176, NOW(), NOW(), 'The Flaming Lips') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (177, NOW(), NOW(), 'Jack''s Mannequin & Mick Fleetwood') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (178, NOW(), NOW(), 'Regina Spektor') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (179, NOW(), NOW(), 'Scorpions') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (180, NOW(), NOW(), 'House Of Pain') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (181, NOW(), NOW(), 'Xis') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (182, NOW(), NOW(), 'Nega Gizza') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (183, NOW(), NOW(), 'Gustavo & Andres Veiga & Salazar') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (184, NOW(), NOW(), 'Rodox') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (185, NOW(), NOW(), 'Charlie Brown Jr.') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (186, NOW(), NOW(), 'Pedro Lu�s E A Parede') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (187, NOW(), NOW(), 'Los Hermanos') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (188, NOW(), NOW(), 'Mundo Livre S/A') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (189, NOW(), NOW(), 'Otto') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (190, NOW(), NOW(), 'Instituto') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (191, NOW(), NOW(), 'Na��o Zumbi') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (192, NOW(), NOW(), 'DJ Dolores & Orchestra Santa Massa') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (193, NOW(), NOW(), 'Seu Jorge') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (194, NOW(), NOW(), 'Sabotage E Instituto') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (195, NOW(), NOW(), 'Stereo Maracana') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (196, NOW(), NOW(), 'Cake') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (197, NOW(), NOW(), 'Aisha Duo') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (198, NOW(), NOW(), 'Habib Koit� and Bamada') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (199, NOW(), NOW(), 'Karsh Kale') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (200, NOW(), NOW(), 'The Posies') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (201, NOW(), NOW(), 'Luciana Souza/Romero Lubambo') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (202, NOW(), NOW(), 'Aaron Goldberg') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (203, NOW(), NOW(), 'Nicolaus Esterhazy Sinfonia') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (204, NOW(), NOW(), 'Temple of the Dog') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (205, NOW(), NOW(), 'Chris Cornell') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (206, NOW(), NOW(), 'Alberto Turco & Nova Schola Gregoriana') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (207, NOW(), NOW(), 'Richard Marlow & The Choir of Trinity College, Cambridge') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (208, NOW(), NOW(), 'English Concert & Trevor Pinnock') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (209, NOW(), NOW(), 'Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (210, NOW(), NOW(), 'Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (211, NOW(), NOW(), 'Wilhelm Kempff') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (212, NOW(), NOW(), 'Yo-Yo Ma') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (213, NOW(), NOW(), 'Scholars Baroque Ensemble') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (214, NOW(), NOW(), 'Academy of St. Martin in the Fields & Sir Neville Marriner') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (215, NOW(), NOW(), 'Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (216, NOW(), NOW(), 'Berliner Philharmoniker, Claudio Abbado & Sabine Meyer') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (217, NOW(), NOW(), 'Royal Philharmonic Orchestra & Sir Thomas Beecham') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (218, NOW(), NOW(), 'Orchestre R�volutionnaire et Romantique & John Eliot Gardiner') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (219, NOW(), NOW(), 'Britten Sinfonia, Ivor Bolton & Lesley Garrett') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (220, NOW(), NOW(), 'Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (221, NOW(), NOW(), 'Sir Georg Solti & Wiener Philharmoniker') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (222, NOW(), NOW(), 'Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (223, NOW(), NOW(), 'London Symphony Orchestra & Sir Charles Mackerras') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (224, NOW(), NOW(), 'Barry Wordsworth & BBC Concert Orchestra') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (225, NOW(), NOW(), 'Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (226, NOW(), NOW(), 'Eugene Ormandy') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (227, NOW(), NOW(), 'Luciano Pavarotti') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (228, NOW(), NOW(), 'Leonard Bernstein & New York Philharmonic') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (229, NOW(), NOW(), 'Boston Symphony Orchestra & Seiji Ozawa') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (230, NOW(), NOW(), 'Aaron Copland & London Symphony Orchestra') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (231, NOW(), NOW(), 'Ton Koopman') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (232, NOW(), NOW(), 'Sergei Prokofiev & Yuri Temirkanov') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (233, NOW(), NOW(), 'Chicago Symphony Orchestra & Fritz Reiner') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (234, NOW(), NOW(), 'Orchestra of The Age of Enlightenment') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (235, NOW(), NOW(), 'Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (236, NOW(), NOW(), 'James Levine') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (237, NOW(), NOW(), 'Berliner Philharmoniker & Hans Rosbaud') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (238, NOW(), NOW(), 'Maurizio Pollini') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (239, NOW(), NOW(), 'Academy of St. Martin in the Fields, Sir Neville Marriner & William Bennett') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (240, NOW(), NOW(), 'Gustav Mahler') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (241, NOW(), NOW(), 'Felix Schmidt, London Symphony Orchestra & Rafael Fr�hbeck de Burgos') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (242, NOW(), NOW(), 'Edo de Waart & San Francisco Symphony') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (243, NOW(), NOW(), 'Antal Dor�ti & London Symphony Orchestra') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (244, NOW(), NOW(), 'Choir Of Westminster Abbey & Simon Preston') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (245, NOW(), NOW(), 'Michael Tilson Thomas & San Francisco Symphony') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (246, NOW(), NOW(), 'Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (247, NOW(), NOW(), 'The King''s Singers') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (248, NOW(), NOW(), 'Berliner Philharmoniker & Herbert Von Karajan') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (249, NOW(), NOW(), 'Sir Georg Solti, Sumi Jo & Wiener Philharmoniker') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (250, NOW(), NOW(), 'Christopher O''Riley') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (251, NOW(), NOW(), 'Fretwork') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (252, NOW(), NOW(), 'Amy Winehouse') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (253, NOW(), NOW(), 'Calexico') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (254, NOW(), NOW(), 'Otto Klemperer & Philharmonia Orchestra') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (255, NOW(), NOW(), 'Yehudi Menuhin') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (256, NOW(), NOW(), 'Philharmonia Orchestra & Sir Neville Marriner') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (257, NOW(), NOW(), 'Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (258, NOW(), NOW(), 'Les Arts Florissants & William Christie') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (259, NOW(), NOW(), 'The 12 Cellists of The Berlin Philharmonic') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (260, NOW(), NOW(), 'Adrian Leaper & Doreen de Feis') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (261, NOW(), NOW(), 'Roger Norrington, London Classical Players') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (262, NOW(), NOW(), 'Charles Dutoit & L''Orchestre Symphonique de Montr�al') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (263, NOW(), NOW(), 'Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (264, NOW(), NOW(), 'Kent Nagano and Orchestre de l''Op�ra de Lyon') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (265, NOW(), NOW(), 'Julian Bream') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (266, NOW(), NOW(), 'Martin Roscoe') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (267, NOW(), NOW(), 'G�teborgs Symfoniker & Neeme J�rvi') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (268, NOW(), NOW(), 'Itzhak Perlman') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (269, NOW(), NOW(), 'Michele Campanella') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (270, NOW(), NOW(), 'Gerald Moore') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (271, NOW(), NOW(), 'Mela Tenenbaum, Pro cataloga Prague & Richard Kapp') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (272, NOW(), NOW(), 'Emerson String Quartet') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (273, NOW(), NOW(), 'C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (274, NOW(), NOW(), 'Nash Ensemble') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.artist ("artist_id", "created_date", "updated_date", "name") VALUES (275, NOW(), NOW(), 'Philip Glass Ensemble') ON CONFLICT DO NOTHING;