INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (1, NOW(), NOW(), 'Rock') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (2, NOW(), NOW(), 'Jazz') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (3, NOW(), NOW(), 'Metal') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (4, NOW(), NOW(), 'Alternative & Punk') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (5, NOW(), NOW(), 'Rock And Roll') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (6, NOW(), NOW(), 'Blues') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (7, NOW(), NOW(), 'Latin') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (8, NOW(), NOW(), 'Reggae') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (9, NOW(), NOW(), 'Pop') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (10, NOW(), NOW(), 'Soundtrack') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (11, NOW(), NOW(), 'Bossa Nova') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (12, NOW(), NOW(), 'Easy Listening') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (13, NOW(), NOW(), 'Heavy Metal') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (14, NOW(), NOW(), 'R&B/Soul') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (15, NOW(), NOW(), 'Electronica/Dance') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (16, NOW(), NOW(), 'World') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (17, NOW(), NOW(), 'Hip Hop/Rap') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (18, NOW(), NOW(), 'Science Fiction') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (19, NOW(), NOW(), 'TV Shows') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (20, NOW(), NOW(), 'Sci Fi & Fantasy') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (21, NOW(), NOW(), 'Drama') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (22, NOW(), NOW(), 'Comedy') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (23, NOW(), NOW(), 'Alternative') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (24, NOW(), NOW(), 'Classical') ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.genre ("genre_id", "created_date", "updated_date", "name") VALUES (25, NOW(), NOW(), 'Opera') ON CONFLICT DO NOTHING;