INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (1, NOW(), NOW(), 'For Those About To Rock We Salute You', 1) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (2, NOW(), NOW(), 'Balls to the Wall', 2) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (3, NOW(), NOW(), 'Restless and Wild', 2) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (4, NOW(), NOW(), 'Let There Be Rock', 1) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (5, NOW(), NOW(), 'Big Ones', 3) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (6, NOW(), NOW(), 'Jagged Little Pill', 4) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (7, NOW(), NOW(), 'Facelift', 5) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (8, NOW(), NOW(), 'Warner 25 Anos', 6) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (9, NOW(), NOW(), 'Plays Metallica By Four Cellos', 7) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (10, NOW(), NOW(), 'Audioslave', 8) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (11, NOW(), NOW(), 'Out Of Exile', 8) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (12, NOW(), NOW(), 'BackBeat Soundtrack', 9) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (13, NOW(), NOW(), 'The Best Of Billy Cobham', 10) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (14, NOW(), NOW(), 'Alcohol Fueled Brewtality Live! [Disc 1]', 11) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (15, NOW(), NOW(), 'Alcohol Fueled Brewtality Live! [Disc 2]', 11) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (16, NOW(), NOW(), 'Black Sabbath', 12) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (17, NOW(), NOW(), 'Black Sabbath Vol. 4 (Remaster)', 12) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (18, NOW(), NOW(), 'Body Count', 13) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (19, NOW(), NOW(), 'Chemical Wedding', 14) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (20, NOW(), NOW(), 'The Best Of Buddy Guy - The Millenium Collection', 15) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (21, NOW(), NOW(), 'Prenda Minha', 16) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (22, NOW(), NOW(), 'Sozinho Remix Ao Vivo', 16) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (23, NOW(), NOW(), 'Minha Historia', 17) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (24, NOW(), NOW(), 'Afrociberdelia', 18) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (25, NOW(), NOW(), 'Da Lama Ao Caos', 18) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (26, NOW(), NOW(), 'Acstico MTV [Live]', 19) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (27, NOW(), NOW(), 'Cidade Negra - Hits', 19) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (28, NOW(), NOW(), 'Na Pista', 20) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (29, NOW(), NOW(), 'Ax Bahia 2001', 21) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (30, NOW(), NOW(), 'BBC Sessions [Disc 1] [Live]', 22) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (31, NOW(), NOW(), 'Bongo Fury', 23) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (32, NOW(), NOW(), 'Carnaval 2001', 21) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (33, NOW(), NOW(), 'Chill: Brazil (Disc 1)', 24) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (34, NOW(), NOW(), 'Chill: Brazil (Disc 2)', 6) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (35, NOW(), NOW(), 'Garage Inc. (Disc 1)', 50) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (36, NOW(), NOW(), 'Greatest Hits II', 51) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (37, NOW(), NOW(), 'Greatest Kiss', 52) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (38, NOW(), NOW(), 'Heart of the Night', 53) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (39, NOW(), NOW(), 'International Superhits', 54) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (40, NOW(), NOW(), 'Into The Light', 55) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (41, NOW(), NOW(), 'Meus Momentos', 56) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (42, NOW(), NOW(), 'Minha Histria', 57) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (43, NOW(), NOW(), 'MK III The Final Concerts [Disc 1]', 58) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (44, NOW(), NOW(), 'Physical Graffiti [Disc 1]', 22) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (45, NOW(), NOW(), 'Sambas De Enredo 2001', 21) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (46, NOW(), NOW(), 'Supernatural', 59) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (47, NOW(), NOW(), 'The Best of Ed Motta', 37) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (48, NOW(), NOW(), 'The Essential Miles Davis [Disc 1]', 68) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (49, NOW(), NOW(), 'The Essential Miles Davis [Disc 2]', 68) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (50, NOW(), NOW(), 'The Final Concerts (Disc 2)', 58) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (51, NOW(), NOW(), 'Up An'' Atom', 69) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (52, NOW(), NOW(), 'Vincius De Moraes - Sem Limite', 70) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (53, NOW(), NOW(), 'Vozes do MPB', 21) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (54, NOW(), NOW(), 'Chronicle, Vol. 1', 76) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (55, NOW(), NOW(), 'Chronicle, Vol. 2', 76) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (56, NOW(), NOW(), 'Cssia Eller - Coleo Sem Limite [Disc 2]', 77) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (57, NOW(), NOW(), 'Cssia Eller - Sem Limite [Disc 1]', 77) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (58, NOW(), NOW(), 'Come Taste The Band', 58) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (59, NOW(), NOW(), 'Deep Purple In Rock', 58) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (60, NOW(), NOW(), 'Fireball', 58) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (61, NOW(), NOW(), 'Knocking at Your Back Door: The Best Of Deep Purple in the 80''s', 58) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (62, NOW(), NOW(), 'Machine Head', 58) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (63, NOW(), NOW(), 'Purpendicular', 58) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (64, NOW(), NOW(), 'Slaves And Masters', 58) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (65, NOW(), NOW(), 'Stormbringer', 58) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (66, NOW(), NOW(), 'The Battle Rages On', 58) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (67, NOW(), NOW(), 'Vault: Def Leppard''s Greatest Hits', 78) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (68, NOW(), NOW(), 'Outbreak', 79) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (69, NOW(), NOW(), 'Djavan Ao Vivo - Vol. 02', 80) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (70, NOW(), NOW(), 'Djavan Ao Vivo - Vol. 1', 80) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (71, NOW(), NOW(), 'Elis Regina-Minha Histria', 41) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (72, NOW(), NOW(), 'The Cream Of Clapton', 81) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (73, NOW(), NOW(), 'Unplugged', 81) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (74, NOW(), NOW(), 'Album Of The Year', 82) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (75, NOW(), NOW(), 'Angel Dust', 82) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (76, NOW(), NOW(), 'King For A Day Fool For A Lifetime', 82) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (77, NOW(), NOW(), 'The Real Thing', 82) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (78, NOW(), NOW(), 'Deixa Entrar', 83) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (79, NOW(), NOW(), 'In Your Honor [Disc 1]', 84) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (80, NOW(), NOW(), 'In Your Honor [Disc 2]', 84) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (81, NOW(), NOW(), 'One By One', 84) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (82, NOW(), NOW(), 'The Colour And The Shape', 84) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (83, NOW(), NOW(), 'My Way: The Best Of Frank Sinatra [Disc 1]', 85) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (84, NOW(), NOW(), 'Roda De Funk', 86) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (85, NOW(), NOW(), 'As Canes de Eu Tu Eles', 27) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (86, NOW(), NOW(), 'Quanta Gente Veio Ver (Live)', 27) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (87, NOW(), NOW(), 'Quanta Gente Veio ver--Bnus De Carnaval', 27) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (88, NOW(), NOW(), 'Faceless', 87) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (89, NOW(), NOW(), 'American Idiot', 54) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (90, NOW(), NOW(), 'Appetite for Destruction', 88) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (91, NOW(), NOW(), 'Use Your Illusion I', 88) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (92, NOW(), NOW(), 'Use Your Illusion II', 88) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (93, NOW(), NOW(), 'Blue Moods', 89) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (94, NOW(), NOW(), 'A Matter of Life and Death', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (95, NOW(), NOW(), 'A Real Dead One', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (96, NOW(), NOW(), 'A Real Live One', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (97, NOW(), NOW(), 'Brave New World', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (98, NOW(), NOW(), 'Dance Of Death', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (99, NOW(), NOW(), 'Fear Of The Dark', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (100, NOW(), NOW(), 'Iron Maiden', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (101, NOW(), NOW(), 'Killers', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (102, NOW(), NOW(), 'Live After Death', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (103, NOW(), NOW(), 'Live At Donington 1992 (Disc 1)', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (104, NOW(), NOW(), 'Live At Donington 1992 (Disc 2)', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (105, NOW(), NOW(), 'No Prayer For The Dying', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (106, NOW(), NOW(), 'Piece Of Mind', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (107, NOW(), NOW(), 'Powerslave', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (108, NOW(), NOW(), 'Rock In Rio [CD1]', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (109, NOW(), NOW(), 'Rock In Rio [CD2]', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (110, NOW(), NOW(), 'Seventh Son of a Seventh Son', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (111, NOW(), NOW(), 'Somewhere in Time', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (112, NOW(), NOW(), 'The Number of The Beast', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (113, NOW(), NOW(), 'The X Factor', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (114, NOW(), NOW(), 'Virtual XI', 90) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (115, NOW(), NOW(), 'Sex Machine', 91) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (116, NOW(), NOW(), 'Emergency On Planet Earth', 92) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (117, NOW(), NOW(), 'Synkronized', 92) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (118, NOW(), NOW(), 'The Return Of The Space Cowboy', 92) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (119, NOW(), NOW(), 'Get Born', 93) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (120, NOW(), NOW(), 'Are You Experienced?', 94) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (121, NOW(), NOW(), 'Surfing with the Alien (Remastered)', 95) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (122, NOW(), NOW(), 'Jorge Ben Jor 25 Anos', 46) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (123, NOW(), NOW(), 'Jota Quest-1995', 96) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (124, NOW(), NOW(), 'Cafezinho', 97) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (125, NOW(), NOW(), 'Living After Midnight', 98) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (126, NOW(), NOW(), 'Unplugged [Live]', 52) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (127, NOW(), NOW(), 'BBC Sessions [Disc 2] [Live]', 22) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (128, NOW(), NOW(), 'Coda', 22) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (129, NOW(), NOW(), 'Houses Of The Holy', 22) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (130, NOW(), NOW(), 'In Through The Out Door', 22) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (131, NOW(), NOW(), 'IV', 22) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (132, NOW(), NOW(), 'Led Zeppelin I', 22) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (133, NOW(), NOW(), 'Led Zeppelin II', 22) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (134, NOW(), NOW(), 'Led Zeppelin III', 22) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (135, NOW(), NOW(), 'Physical Graffiti [Disc 2]', 22) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (136, NOW(), NOW(), 'Presence', 22) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (137, NOW(), NOW(), 'The Song Remains The Same (Disc 1)', 22) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (138, NOW(), NOW(), 'The Song Remains The Same (Disc 2)', 22) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (139, NOW(), NOW(), 'A TempestadeTempestade Ou O Livro Dos Dias', 99) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (140, NOW(), NOW(), 'Mais Do Mesmo', 99) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (141, NOW(), NOW(), 'Greatest Hits', 100) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (142, NOW(), NOW(), 'Lulu Santos - RCA 100 Anos De Msica - lbum 01', 101) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (143, NOW(), NOW(), 'Lulu Santos - RCA 100 Anos De Msica - lbum 02', 101) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (144, NOW(), NOW(), 'Misplaced Childhood', 102) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (145, NOW(), NOW(), 'Barulhinho Bom', 103) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (146, NOW(), NOW(), 'Seek And Shall Find: More Of The Best (1963-1981)', 104) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (147, NOW(), NOW(), 'The Best Of Men At Work', 105) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (148, NOW(), NOW(), 'Black Album', 50) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (149, NOW(), NOW(), 'Garage Inc. (Disc 2)', 50) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (150, NOW(), NOW(), 'Kill ''Em All', 50) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (151, NOW(), NOW(), 'Load', 50) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (152, NOW(), NOW(), 'Master Of Puppets', 50) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (153, NOW(), NOW(), 'ReLoad', 50) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (154, NOW(), NOW(), 'Ride The Lightning', 50) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (155, NOW(), NOW(), 'St. Anger', 50) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (156, NOW(), NOW(), '...And Justice For All', 50) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (157, NOW(), NOW(), 'Miles Ahead', 68) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (158, NOW(), NOW(), 'Milton Nascimento Ao Vivo', 42) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (159, NOW(), NOW(), 'Minas', 42) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (160, NOW(), NOW(), 'Ace Of Spades', 106) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (161, NOW(), NOW(), 'Demorou...', 108) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (162, NOW(), NOW(), 'Motley Crue Greatest Hits', 109) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (163, NOW(), NOW(), 'From The Muddy Banks Of The Wishkah [Live]', 110) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (164, NOW(), NOW(), 'Nevermind', 110) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (165, NOW(), NOW(), 'Compositores', 111) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (166, NOW(), NOW(), 'Olodum', 112) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (167, NOW(), NOW(), 'Acstico MTV', 113) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (168, NOW(), NOW(), 'Arquivo II', 113) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (169, NOW(), NOW(), 'Arquivo Os Paralamas Do Sucesso', 113) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (170, NOW(), NOW(), 'Bark at the Moon (Remastered)', 114) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (171, NOW(), NOW(), 'Blizzard of Ozz', 114) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (172, NOW(), NOW(), 'Diary of a Madman (Remastered)', 114) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (173, NOW(), NOW(), 'No More Tears (Remastered)', 114) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (174, NOW(), NOW(), 'Tribute', 114) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (175, NOW(), NOW(), 'Walking Into Clarksdale', 115) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (176, NOW(), NOW(), 'Original Soundtracks 1', 116) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (177, NOW(), NOW(), 'The Beast Live', 117) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (178, NOW(), NOW(), 'Live On Two Legs [Live]', 118) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (179, NOW(), NOW(), 'Pearl Jam', 118) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (180, NOW(), NOW(), 'Riot Act', 118) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (181, NOW(), NOW(), 'Ten', 118) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (182, NOW(), NOW(), 'Vs.', 118) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (183, NOW(), NOW(), 'Dark Side Of The Moon', 120) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (184, NOW(), NOW(), 'Os Ces Ladram Mas A Caravana No Pra', 121) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (185, NOW(), NOW(), 'Greatest Hits I', 51) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (186, NOW(), NOW(), 'News Of The World', 51) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (187, NOW(), NOW(), 'Out Of Time', 122) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (188, NOW(), NOW(), 'Green', 124) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (189, NOW(), NOW(), 'New Adventures In Hi-Fi', 124) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (190, NOW(), NOW(), 'The Best Of R.E.M.: The IRS Years', 124) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (191, NOW(), NOW(), 'Cesta Bsica', 125) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (192, NOW(), NOW(), 'Raul Seixas', 126) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (193, NOW(), NOW(), 'Blood Sugar Sex Magik', 127) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (194, NOW(), NOW(), 'By The Way', 127) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (195, NOW(), NOW(), 'Californication', 127) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (196, NOW(), NOW(), 'Retrospective I (1974-1980)', 128) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (197, NOW(), NOW(), 'Santana - As Years Go By', 59) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (198, NOW(), NOW(), 'Santana Live', 59) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (199, NOW(), NOW(), 'Maquinarama', 130) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (200, NOW(), NOW(), 'O Samba Pocon', 130) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (201, NOW(), NOW(), 'Judas 0: B-Sides and Rarities', 131) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (202, NOW(), NOW(), 'Rotten Apples: Greatest Hits', 131) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (203, NOW(), NOW(), 'A-Sides', 132) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (204, NOW(), NOW(), 'Morning Dance', 53) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (205, NOW(), NOW(), 'In Step', 133) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (206, NOW(), NOW(), 'Core', 134) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (207, NOW(), NOW(), 'Mezmerize', 135) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (208, NOW(), NOW(), '[1997] Black Light Syndrome', 136) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (209, NOW(), NOW(), 'Live [Disc 1]', 137) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (210, NOW(), NOW(), 'Live [Disc 2]', 137) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (211, NOW(), NOW(), 'The Singles', 138) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (212, NOW(), NOW(), 'Beyond Good And Evil', 139) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (213, NOW(), NOW(), 'Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]', 139) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (214, NOW(), NOW(), 'The Doors', 140) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (215, NOW(), NOW(), 'The Police Greatest Hits', 141) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (216, NOW(), NOW(), 'Hot Rocks, 1964-1971 (Disc 1)', 142) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (217, NOW(), NOW(), 'No Security', 142) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (218, NOW(), NOW(), 'Voodoo Lounge', 142) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (219, NOW(), NOW(), 'Tangents', 143) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (220, NOW(), NOW(), 'Transmission', 143) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (221, NOW(), NOW(), 'My Generation - The Very Best Of The Who', 144) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (222, NOW(), NOW(), 'Serie Sem Limite (Disc 1)', 145) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (223, NOW(), NOW(), 'Serie Sem Limite (Disc 2)', 145) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (224, NOW(), NOW(), 'Acstico', 146) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (225, NOW(), NOW(), 'Volume Dois', 146) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (226, NOW(), NOW(), 'Battlestar Galactica: The Story So Far', 147) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (227, NOW(), NOW(), 'Battlestar Galactica, Season 3', 147) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (228, NOW(), NOW(), 'Heroes, Season 1', 148) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (229, NOW(), NOW(), 'Lost, Season 3', 149) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (230, NOW(), NOW(), 'Lost, Season 1', 149) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (231, NOW(), NOW(), 'Lost, Season 2', 149) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (232, NOW(), NOW(), 'Achtung Baby', 150) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (233, NOW(), NOW(), 'All That You Can''t Leave Behind', 150) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (234, NOW(), NOW(), 'B-Sides 1980-1990', 150) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (235, NOW(), NOW(), 'How To Dismantle An Atomic Bomb', 150) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (236, NOW(), NOW(), 'Pop', 150) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (237, NOW(), NOW(), 'Rattle And Hum', 150) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (238, NOW(), NOW(), 'The Best Of 1980-1990', 150) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (239, NOW(), NOW(), 'War', 150) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (240, NOW(), NOW(), 'Zooropa', 150) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (241, NOW(), NOW(), 'UB40 The Best Of - Volume Two [UK]', 151) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (242, NOW(), NOW(), 'Diver Down', 152) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (243, NOW(), NOW(), 'The Best Of Van Halen, Vol. I', 152) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (244, NOW(), NOW(), 'Van Halen', 152) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (245, NOW(), NOW(), 'Van Halen III', 152) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (246, NOW(), NOW(), 'Contraband', 153) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (247, NOW(), NOW(), 'Vinicius De Moraes', 72) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (248, NOW(), NOW(), 'Ao Vivo [IMPORT]', 155) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (249, NOW(), NOW(), 'The Office, Season 1', 156) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (250, NOW(), NOW(), 'The Office, Season 2', 156) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (251, NOW(), NOW(), 'The Office, Season 3', 156) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (252, NOW(), NOW(), 'Un-Led-Ed', 157) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (253, NOW(), NOW(), 'Battlestar Galactica (Classic), Season 1', 158) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (254, NOW(), NOW(), 'Aquaman', 159) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (255, NOW(), NOW(), 'Instant Karma: The Amnesty International Campaign to Save Darfur', 150) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (256, NOW(), NOW(), 'Speak of the Devil', 114) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (257, NOW(), NOW(), '20th Century Masters - The Millennium Collection: The Best of Scorpions', 179) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (258, NOW(), NOW(), 'House of Pain', 180) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (259, NOW(), NOW(), 'Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro', 36) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (260, NOW(), NOW(), 'Cake: B-Sides and Rarities', 196) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (261, NOW(), NOW(), 'LOST, Season 4', 149) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (262, NOW(), NOW(), 'Quiet Songs', 197) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (263, NOW(), NOW(), 'Muso Ko', 198) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (264, NOW(), NOW(), 'Realize', 199) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (265, NOW(), NOW(), 'Every Kind of Light', 200) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (266, NOW(), NOW(), 'Duos II', 201) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (267, NOW(), NOW(), 'Worlds', 202) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (268, NOW(), NOW(), 'The Best of Beethoven', 203) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (269, NOW(), NOW(), 'Temple of the Dog', 204) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (270, NOW(), NOW(), 'Carry On', 205) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (271, NOW(), NOW(), 'Revelations', 8) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (272, NOW(), NOW(), 'Adorate Deum: Gregorian Chant from the Proper of the Mass', 206) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (273, NOW(), NOW(), 'Allegri: Miserere', 207) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (274, NOW(), NOW(), 'Pachelbel: Canon & Gigue', 208) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (275, NOW(), NOW(), 'Vivaldi: The Four Seasons', 209) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (276, NOW(), NOW(), 'Bach: Violin Concertos', 210) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (277, NOW(), NOW(), 'Bach: Goldberg Variations', 211) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (278, NOW(), NOW(), 'Bach: The Cello Suites', 212) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (279, NOW(), NOW(), 'Handel: The Messiah (Highlights)', 213) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (280, NOW(), NOW(), 'The World of Classical Favourites', 214) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (281, NOW(), NOW(), 'Sir Neville Marriner: A Celebration', 215) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (282, NOW(), NOW(), 'Mozart: Wind Concertos', 216) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (283, NOW(), NOW(), 'Haydn: Symphonies 99 - 104', 217) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (284, NOW(), NOW(), 'Beethoven: Symhonies Nos. 5 & 6', 218) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (285, NOW(), NOW(), 'A Soprano Inspired', 219) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (286, NOW(), NOW(), 'Great Opera Choruses', 220) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (287, NOW(), NOW(), 'Wagner: Favourite Overtures', 221) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (288, NOW(), NOW(), 'Faur: Requiem, Ravel: Pavane & Others', 222) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (289, NOW(), NOW(), 'Tchaikovsky: The Nutcracker', 223) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (290, NOW(), NOW(), 'The Last Night of the Proms', 224) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (291, NOW(), NOW(), 'Puccini: Madama Butterfly - Highlights', 225) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (292, NOW(), NOW(), 'Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies', 226) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (293, NOW(), NOW(), 'Pavarotti''s Opera Made Easy', 227) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (294, NOW(), NOW(), 'Great Performances - Barber''s Adagio and Other Romantic Favorites for Strings', 228) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (295, NOW(), NOW(), 'Carmina Burana', 229) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (296, NOW(), NOW(), 'A Copland Celebration, Vol. I', 230) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (297, NOW(), NOW(), 'Bach: Toccata & Fugue in D Minor', 231) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (298, NOW(), NOW(), 'Prokofiev: Symphony No.1', 232) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (299, NOW(), NOW(), 'Scheherazade', 233) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (300, NOW(), NOW(), 'Bach: The Brandenburg Concertos', 234) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (301, NOW(), NOW(), 'Chopin: Piano Concertos Nos. 1 & 2', 235) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (302, NOW(), NOW(), 'Mascagni: Cavalleria Rusticana', 236) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (303, NOW(), NOW(), 'Sibelius: Finlandia', 237) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (304, NOW(), NOW(), 'Beethoven Piano Sonatas: Moonlight & Pastorale', 238) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (305, NOW(), NOW(), 'Great Recordings of the Century - Mahler: Das Lied von der Erde', 240) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (306, NOW(), NOW(), 'Elgar: Cello Concerto & Vaughan Williams: Fantasias', 241) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (307, NOW(), NOW(), 'Adams, John: The Chairman Dances', 242) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (308, NOW(), NOW(), 'Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington''s Victory', 243) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (309, NOW(), NOW(), 'Palestrina: Missa Papae Marcelli & Allegri: Miserere', 244) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (310, NOW(), NOW(), 'Prokofiev: Romeo & Juliet', 245) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (311, NOW(), NOW(), 'Strauss: Waltzes', 226) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (312, NOW(), NOW(), 'Berlioz: Symphonie Fantastique', 245) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (313, NOW(), NOW(), 'Bizet: Carmen Highlights', 246) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (314, NOW(), NOW(), 'English Renaissance', 247) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (315, NOW(), NOW(), 'Handel: catalog for the Royal Fireworks (Original Version 1749)', 208) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (316, NOW(), NOW(), 'Grieg: Peer Gynt Suites & Sibelius: Pellas et Mlisande', 248) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (317, NOW(), NOW(), 'Mozart Gala: Famous Arias', 249) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (318, NOW(), NOW(), 'SCRIABIN: Vers la flamme', 250) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (319, NOW(), NOW(), 'Armada: catalog from the Courts of England and Spain', 251) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (320, NOW(), NOW(), 'Mozart: Symphonies Nos. 40 & 41', 248) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (321, NOW(), NOW(), 'Back to Black', 252) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (322, NOW(), NOW(), 'Frank', 252) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (323, NOW(), NOW(), 'Carried to Dust (Bonus Track Version)', 253) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (324, NOW(), NOW(), 'Beethoven: Symphony No. 6 ''Pastoral'' Etc.', 254) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (325, NOW(), NOW(), 'Bartok: Violin & Viola Concertos', 255) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (326, NOW(), NOW(), 'Mendelssohn: A Midsummer Night''s Dream', 256) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (327, NOW(), NOW(), 'Bach: Orchestral Suites Nos. 1 - 4', 257) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (328, NOW(), NOW(), 'Charpentier: Divertissements, Airs & Concerts', 258) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (329, NOW(), NOW(), 'South American Getaway', 259) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (330, NOW(), NOW(), 'Grecki: Symphony No. 3', 260) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (331, NOW(), NOW(), 'Purcell: The Fairy Queen', 261) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (332, NOW(), NOW(), 'The Ultimate Relexation Album', 262) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (333, NOW(), NOW(), 'Purcell: catalog for the Queen Mary', 263) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (334, NOW(), NOW(), 'Weill: The Seven Deadly Sins', 264) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (335, NOW(), NOW(), 'J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro', 265) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (336, NOW(), NOW(), 'Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps', 248) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (337, NOW(), NOW(), 'Szymanowski: Piano Works, Vol. 1', 266) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (338, NOW(), NOW(), 'Nielsen: The Six Symphonies', 267) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (339, NOW(), NOW(), 'Great Recordings of the Century: Paganini''s 24 Caprices', 268) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (340, NOW(), NOW(), 'Liszt - 12 tudes D''Execution Transcendante', 269) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (341, NOW(), NOW(), 'Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder', 270) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (342, NOW(), NOW(), 'Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3', 271) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (343, NOW(), NOW(), 'Respighi:Pines of Rome', 226) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (344, NOW(), NOW(), 'Schubert: The Late String Quartets & String Quintet (3 CD''s)', 272) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (345, NOW(), NOW(), 'Monteverdi: L''Orfeo', 273) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (346, NOW(), NOW(), 'Mozart: Chamber catalog', 274) ON CONFLICT DO NOTHING;
INSERT INTO music_catalog.album ("album_id", "created_date", "updated_date", "title", "artist_id") VALUES (347, NOW(), NOW(), 'Koyaanisqatsi (Soundtrack from the Motion Picture)', 275) ON CONFLICT DO NOTHING;